ALTER TABLE `ajusteinv`
	ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `fecha`;
ALTER TABLE `compra`
	ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `fecha`;
ALTER TABLE `cotizacion`
	ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `fecha`;
ALTER TABLE `factura`
	ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `fecha`;
ALTER TABLE `ordencompra`
	ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `fecha`;
ALTER TABLE `producto` 
        ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `fecha_creacion`;
ALTER TABLE `proveedor` 
        ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `estatus`;
ALTER TABLE `cliente` 
        ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `estatus`;
ALTER TABLE `notasalida` 
        ADD COLUMN `actualizado` TIMESTAMP NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP AFTER `estatus`