<?php 
 return array(
    'Cliente' => 19,
    'Compra' => 12,
    'Config' => 1,
    'Cotizacion' => 19,
    'Departamento' => 14,
    'Dolares' => 4,
    'Factura' => 6,
    'Nota' => 3,
    'Orden' => 1,
    'Plantilla' => 4,
    'Producto' => 115,
    'Proveedor' => 1,
    'Tipo' => 47,
    'Unidad' => 4,
    'Usuario' => 59,
    'Moneda' => 14,
    'Ajuste' => 419,
);