<?php 
 return array(
    'Cliente' => 63,
    'Compra' => 3,
    'Config' => 1,
    'Cotizacion' => 3,
    'Departamento' => 1,
    'Dolares' => 3,
    'Factura' => 1,
    'Nota' => 15,
    'Orden' => 1,
    'Plantilla' => 9,
    'Producto' => 149,
    'Proveedor' => 56,
    'Tipo' => 1,
    'Unidad' => 1,
    'Usuario' => 3,
    'Moneda' => 1,
    'Ajuste' => 1,
);