<?php 
 return array(
    'Cliente' => 13,
    'Compra' => 2,
    'Config' => 1,
    'Cotizacion' => 11,
    'Departamento' => 14,
    'Dolares' => 3,
    'Factura' => 4,
    'Nota' => 1,
    'Orden' => 1,
    'Plantilla' => 1,
    'Producto' => 53,
    'Proveedor' => 1,
    'Tipo' => 47,
    'Unidad' => 4,
    'Usuario' => 52,
    '' => 9,
    'Moneda' => 14,
    'Ajuste' => 415,
);