<?php 
 return array(
    'Ajuste' => 421,
    'Cliente' => 26,
    'Compra' => 23,
    'Config' => 1,
    'Cotizacion' => 41,
    'Departamento' => 14,
    'Dolares' => 14,
    'Factura' => 15,
    'Moneda' => 14,
    'Nota' => 7,
    'Orden' => 3,
    'Plantilla' => 4,
    'Producto' => 185,
    'Proveedor' => 11,
    'Tipo' => 47,
    'Unidad' => 4,
    'Usuario' => 68,
);