<?php 
 return array(
    'garantia' => 'GARANTIA DEL PRODUCTO VARIA SEGÚN EL FABRICANTE O PROVEEDOR',
    'observacion' => 'EL PRECIO INDICADO ES EL TOTAL A CANCELAR INCLUYE FLETE Y ENTREGA EN BARQUISIMETO',
);